language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- 3.7-dev
- 3.8-dev
- nightly
- pypy
- pypy3
install:
- travis_retry pip install coveralls
script:
- coverage run --source=jsonpointer tests.py
after_script:
- coveralls
sudo: false
addons:
  apt:
    packages:
    - pandoc
before_deploy:
- pip install -r requirements-dev.txt
deploy:
  provider: pypi
  user: skoegl
  password:
    secure: bKET/1sK+uWetPM3opPTt4qHHfZ6bMcjuLGe3Z/EUfNnGazcbDezy9CHJSqofuMXynF3xc8yluEojjfaqos3Ge/Y4o8pdFMY8ABp8KkxMnAJYGtYzbneSHgdgxPKsmdcUMVtIfioqkeNJTJClWUhRikWSlpKZ7TtkK4AmWtKNwc=
  on:
    tags: true
  distributions: sdist bdist_wheel
